CREATE TABLE Suppliers (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL,
  Email VARCHAR(50) UNIQUE NOT NULL,
  PhoneNumber VARCHAR(50) UNIQUE NOT NULL,
  Address NVARCHAR(500) NOT NULL
);