CREATE TABLE Products (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL UNIQUE,
  Price DECIMAL(18, 2) NOT NULL,
  Discount DECIMAL(18, 2) NOT NULL DEFAULT 0,
  Stock DECIMAL(18, 2) NOT NULL DEFAULT 0,
  CategoryId INT NOT NULL,
  SupplierId INT NOT NULL,
  Description TEXT NULL,
  FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
  FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id)
);
